// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesMediaCards from '@/components/sections/features/FeaturesMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesMediaCards
          tag="Why Compustar"
          title="Better Parts. Bigger Possibilities."
          description="We ensure every build and component meets the highest standards of performance and reliability."
          items={[
            {
              title: "100% Genuine Products",
              description: "Authentic hardware with full manufacturer warranty support.",
              imageSrc: "http://img.b2bpic.net/free-photo/person-using-ar-technology-perform-their-occupation_23-2151137479.jpg",
            },
            {
              title: "Fast Delivery",
              description: "Across India, we ensure your components arrive safely and on time.",
              imageSrc: "http://img.b2bpic.net/free-photo/circuit-board-close-up-with-different-components_23-2149174308.jpg",
            },
            {
              title: "Expert Support",
              description: "Technical guidance from enthusiasts who actually build the machines.",
              imageSrc: "http://img.b2bpic.net/free-photo/dark-style-lamp-design_23-2151105934.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
