// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitVerticalMarquee from '@/components/sections/hero/HeroSplitVerticalMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitVerticalMarquee
          tag="Your Ultimate PC Store"
          title="COMPUSTAR"
          description="Dream. Build. Play. Premium computer parts. Genuine products. Better performance. No compromises."
          primaryButton={{
            text: "Explore Products",
            href: "#products",
          }}
          secondaryButton={{
            text: "Build Your PC",
            href: "#build",
          }}
          leftItems={[
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3HweT5uwSMtSyntCQeShb6NrmLY/uploaded-1786791480720-2qjcav09.png?_wi=1",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/cyberpunk-circuit-board_23-2151977489.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/neon-motherboard-background_23-2151704830.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/hard-drive-with-blue-light-laptop-high-angle_23-2149417021.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/technology-background-texture_23-2148105508.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/industry-40-photovoltaics-plant-admin-using-digital-device-app_482257-126123.jpg",
            },
          ]}
          rightItems={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-rgb-led-lights-system-desktop-woman-gamer-playing-space-shoother-video-games-online-championship-gaming-studio-equipped-with-professional-streaming-setup_482257-29255.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/electronic-waste-isolated-white_93675-135866.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/flat-lay-storage-device-laptop_23-2149319341.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/technology-background-texture_23-2148105522.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-hard-drive-components_23-2149413382.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3HweT5uwSMtSyntCQeShb6NrmLY/uploaded-1786791480720-2qjcav09.png?_wi=2",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
