// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Our Impact"
          title="Built for Performance"
          description="Empowering creators and gamers across the nation."
          metrics={[
            {
              value: "15,000+",
              description: "PCs Built",
            },
            {
              value: "4.9/5",
              description: "Customer Rating",
            },
            {
              value: "24h",
              description: "Support Response",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
