// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingMediaCards from '@/components/sections/pricing/PricingMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingMediaCards
          tag="Build Plans"
          title="Expert Custom Builds"
          description="Tiered configurations tailored to your needs."
          plans={[
            {
              tag: "Starter",
              price: "₹45,000",
              period: "/unit",
              features: [
                "Entry Gaming",
                "4K Video Editing",
                "1 Year Support",
              ],
              primaryButton: {
                text: "Select",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/red-themed-motherboard-with-memory-slots_23-2148284296.jpg",
            },
            {
              tag: "Enthusiast",
              price: "₹95,000",
              period: "/unit",
              features: [
                "Advanced Gaming",
                "3D Rendering",
                "2 Year Support",
              ],
              primaryButton: {
                text: "Select",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/high-angle-hard-drive-components-blue-light_23-2149417026.jpg",
            },
            {
              tag: "Professional",
              price: "₹1,85,000",
              period: "/unit",
              features: [
                "Ultimate Power",
                "Multi-Tasking",
                "Lifetime Support",
              ],
              primaryButton: {
                text: "Select",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/smart-microchip-background-motherboard-closeup-technology_53876-124725.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
