// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "products" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductsSection(): React.JSX.Element {
  return (
    <div id="products" data-section="products">
        <SectionErrorBoundary name="products">
              <FeaturesRevealCardsBento
          tag="Curated Hardware"
          title="Showroom Experience"
          description="Browse our hand-picked selection of high-performance components."
          items={[
            {
              title: "Processors",
              description: "High-speed CPUs for gaming and work.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/control-table-spacecraft-from-inside_23-2151828148.jpg",
            },
            {
              title: "Cooling",
              description: "Keep your system frosty under pressure.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/cpu-processor-motherboard_53876-96834.jpg",
            },
            {
              title: "Cases",
              description: "Sleek chassis for every aesthetic.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/headphones-chair-gaming-setup_23-2149829131.jpg",
            },
            {
              title: "Graphics Cards",
              description: "Powering your visual experiences.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/circuit-board-close-up-with-different-components_23-2149174325.jpg",
            },
            {
              title: "Storage",
              description: "Lightning-fast NVMe and SSD drives.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/usb-type-c-port-warm-neon-scene-tech-macro_169016-71583.jpg",
            },
            {
              title: "Power Supplies",
              description: "Reliable, efficient energy delivery.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/technology-texture-background_23-2148105458.jpg",
            },
            {
              title: "Motherboards",
              description: "The foundation of your dream build.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/technology-background-texture_23-2148105510.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
