// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamProfileCards from '@/components/sections/team/TeamProfileCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamProfileCards
          tag="Meet Our Experts"
          title="The Builders Behind Compustar"
          description="Technically adept professionals dedicated to quality."
          items={[
            {
              title: "Aarav Sharma",
              description: "Lead PC Building Specialist & Enthusiast.",
              avatarSrc: "http://img.b2bpic.net/free-photo/middle-aged-hispanic-business-person_23-2151099201.jpg",
              buttonText: "View Profile",
              imageSrc: "http://img.b2bpic.net/free-photo/neon-robot-vacuum-cleaner_23-2151349307.jpg",
            },
            {
              title: "Priya Iyer",
              description: "Hardware Performance Optimization Lead.",
              avatarSrc: "http://img.b2bpic.net/free-photo/brunette-businesswoman-posing_23-2148142754.jpg",
              buttonText: "View Profile",
              imageSrc: "http://img.b2bpic.net/free-photo/3d-fantasy-scene_23-2151128042.jpg",
            },
            {
              title: "Vikram Singh",
              description: "Systems Architecture & Support Chief.",
              avatarSrc: "http://img.b2bpic.net/free-photo/positive-hipster-entrepreneur-it-expert-software-developer_74855-3635.jpg",
              buttonText: "View Profile",
              imageSrc: "http://img.b2bpic.net/free-photo/prism-dispersing-light-concept_23-2148599231.jpg",
            },
            {
              title: "Ananya Reddy",
              description: "Client Experience & Build Specialist.",
              avatarSrc: "http://img.b2bpic.net/free-photo/closeup-content-pretty-businesswoman-glasses_1262-1740.jpg",
              buttonText: "View Profile",
              imageSrc: "http://img.b2bpic.net/free-photo/neon-motherboard-background_23-2151704761.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
