// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonial" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialSection(): React.JSX.Element {
  return (
    <div id="testimonial" data-section="testimonial">
        <SectionErrorBoundary name="testimonial">
              <TestimonialMarqueeCards
          tag="Our Clients"
          title="Voices of Excellence"
          description="Trusted by enthusiasts and creators throughout India."
          testimonials={[
            {
              name: "Rahul Verma",
              role: "Pro Gamer",
              quote: "The best PC build experience ever! Truly premium components.",
              imageSrc: "http://img.b2bpic.net/free-photo/joyful-young-woman-with-pixie-haircut-looking-side_141793-33142.jpg",
            },
            {
              name: "Sunita Rao",
              role: "3D Artist",
              quote: "My new workstation is a monster. Thanks Compustar team!",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-young-female-with-hair-bun-having-joyful-look-smiling-cheerfully-happy-with-some-positive-news_273609-9042.jpg",
            },
            {
              name: "Amit Kumar",
              role: "Video Editor",
              quote: "Genuine parts, great packaging, expert assistance.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-young-businessman-suit-looking-camera-meeting_1163-4654.jpg",
            },
            {
              name: "Divya M.",
              role: "Developer",
              quote: "Build quality is unmatched. Would buy again.",
              imageSrc: "http://img.b2bpic.net/free-photo/front-view-son-father-playing-music_23-2148404197.jpg",
            },
            {
              name: "Karthik J.",
              role: "Creator",
              quote: "Finally found a place that takes PC builds seriously.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-handsome-man-using-tablet-night-city-lights_23-2149024666.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
